# permissions for end users to view backuppodsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backuppodset-viewer-role
rules:
- apiGroups:
  - backup.example.com
  resources:
  - backuppodsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.example.com
  resources:
  - backuppodsets/status
  verbs:
  - get
